services:
  - type: web
    name: atom-bowl
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
      - key: PYTHON
        value: python3
      - key: RUBY
        value: ruby
